version: '2'
services:
  eltrauaa-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/EltraUAA/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=EltraUAA
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
